### ISSUE TITLE
Allow string source to be passed into createRegistry directly

### ISSUE THREAD

**Issue by nishtahir** [PanAeon/vscode-tmgrammar-test#13]
It would be nice if there was an overload for `createRegistry` that could accept a string source directly here - https://github.com/PanAeon/vscode-tmgrammar-test/blob/1346524c394c08b21926518148a926312c6076ab/src/unit/index.ts#L72

This would eliminate the need to write to disk when the source has already been loaded such as in my usecase here
https://github.com/nishtahir/language-kotlin/blob/eb0b0ba08125510bcfa19ae72a9fc01fde3ce4ad/scripts/coverage.js#L32

**Comment by PanAeon** [comment]
@nishtahir  I'll add an overload, but atm you're using internal code not meant to be exported :smiley_cat: New features can easily break your code... Love your idea of a code coverage tool, though :+1:

**Comment by nishtahir** [comment]
I figured that was the case. I thought that this could be a good starting point for some conversations about a stable public API.
