### ISSUE TITLE
Validation of grammars

### ISSUE THREAD

**Issue by 4086606** [PanAeon/vscode-tmgrammar-test#26]
@PanAeon could you give a CLI command to just validate grammars and see if they can load?

**Comment by PanAeon** [comment]
There's no such command atm. Could be easily added I think.

**Comment by 4086606** [comment]
Yup, add an option to return at this line with a successful exit code:

https://github.com/PanAeon/vscode-tmgrammar-test/blob/7dabf209f43ac85f5dbfaf7b202230fb99d86dbc/src/unit.ts#L79

**Comment by 4086606** [comment]
Is it okay if I make a PR for this?

**Comment by ryanblock** [comment]
Hey, did this option not get released?

**Comment by SNDST00M** [comment]
It wasn't released as we didn't get pattern validation implemented. Fwiw it's a matter of writing a Ruby/JS script that recursively lifts all patterns into an array then tries to initialise all of them as Oniguruma regexp
