### ISSUE TITLE
Can't test grammars that depend on other scopes

### ISSUE THREAD

**Issue by NTaylorMullen** [PanAeon/vscode-tmgrammar-test#3]
For instance, you can't write tests against: https://github.com/microsoft/vscode/blob/master/extensions/razor/syntaxes/cshtml.tmLanguage.json

Because it depends on the HTML grammar: https://github.com/microsoft/vscode/blob/master/extensions/razor/syntaxes/cshtml.tmLanguage.json#L36

And it depends on the C# grammar: https://github.com/microsoft/vscode/blob/master/extensions/razor/syntaxes/cshtml.tmLanguage.json#L89

When you attempt to write a .cshtml test you end up getting:
```
grammar not found for 'source.cs'
grammar not found for 'text.html.basic'
```

If the --grammar accepted multiple grammars it could pre-load them into the textmate registry which would resolve this.

**Comment by PanAeon** [comment]
This issue is fixed in the [0.0.8](https://github.com/PanAeon/vscode-tmgrammar-test/releases/tag/v0.0.8)
To specify multiple grammars you'll need to repeat grammar option, e.g.: 
```
vscode-tmgrammar-test -g csharp.tmLanguage.json -g cshtml.tmLanguage.json -g html.tmLanguage.json ...
```
