### ISSUE TITLE
Clarify implications of `-s` removal in 0.1.1

### ISSUE THREAD

**Issue by radeksimko** [PanAeon/vscode-tmgrammar-test#38]
It seems to me that the following note in the recent changelog is not true:

> remove '--scope' option from vscode-tmgrammar-test. Unit tests got scope information from their header so it wasn't doing anything

At least all of our snap tests, which were passing before are now failing, e.g.

```
ERROR can't run testcase: tests/snapshot/hcl/basic.hcl
No scope is associated with the file.
```

https://github.com/hashicorp/syntax/runs/6269178793?check_suite_focus=true#step:5:16

https://github.com/hashicorp/syntax/pull/33

Was that intended? If so - what was the motivation behind making these scopes explicit within the files?

**Comment by PanAeon** [comment]
Hi, 
the `-s` option has been removed from the `vscode-tmgrammar-test` specifically. You can still use it for the `vscode-tmgrammar-snap`. 
The unit tests has been designed to have a top grammar scope in their header. This whole options was an overlook on my part, as the `--scope` option was originally meant to be for the grammar, so unit tests could link against it. But for the `snap` tests you can continue to use it to indicate the scope of the testcases.
Also now [both programs can read necessary metadata from the package json.](https://github.com/PanAeon/vscode-tmgrammar-test#language-configuration-via-packagejson) This way no additional configuration via command line options is necessary.

**Comment by radeksimko** [comment]
> You can still use it for the vscode-tmgrammar-snap.

Indeed - I don't know how could I miss that 😅  Thanks!

> Also now [both programs can read necessary metadata from the package json.](https://github.com/PanAeon/vscode-tmgrammar-test#language-configuration-via-packagejson) This way no additional configuration via command line options is necessary.

Understood, but we maintain our grammars in a separate repository, away from the extensions themselves, so this doesn't apply to us, but it does sound like a useful default for the majority of users!
