### ISSUE TITLE
Option to Limit Concurrent Tests for Improved Performance

### ISSUE THREAD

**Issue by hankhsu1996** [PanAeon/vscode-tmgrammar-test#49]
I've encountered a performance issue with a complex grammar (several thousand lines of tmLanguage). When running a small number of tests (around 10), the tests complete in a few seconds. However, with approximately 50 tests, the duration extends to a few minutes. Beyond 70 tests, the process seems to run indefinitely.

Experimenting with a concurrency limit of 10 asynchronous functions, I've found a notable improvement. This change reduced the execution time from indefinite to just 2.5 seconds for all tests. Therefore, I suggest implementing an option to limit test concurrency, enhancing performance for large and complex test suites.

Here is the function I used to replace `Promise.all`:

```typescript
const concurrencyLimit = 10

async function promiseAllWithConcurrencyLimit<T>(promises: (() => Promise<T>)[], limit: number): Promise<T[]> {
  const results: Promise<T>[] = []
  const executing = new Set<Promise<any>>()

  for (const promise of promises) {
    const p = promise().then((res) => {
      executing.delete(p)
      return res
    })

    results.push(p)
    executing.add(p)

    if (executing.size >= limit) {
      await Promise.race(executing)
    }
  }

  return Promise.all(results)
}

const testResults: Promise<number[]> = promiseAllWithConcurrencyLimit(
  rawTestCases.map((filename) => (): Promise<number> => {
    let tc: GrammarTestCase | undefined = undefined
    try {
      tc = parseGrammarTestCase(fs.readFileSync(filename).toString())
    } catch (error) {
      reporter.reportParseError(filename, error)
      return new Promise((resolve) => {
        resolve(TestFailed)
      })
    }
    let testCase = tc as GrammarTestCase
    return runGrammarTestCase(registry, testCase)
      .then((failures) => {
        reporter.reportTestResult(filename, testCase, failures)
        return failures.length === 0 ? TestSuccessful : TestFailed
      })
      .catch((error: any) => {
        reporter.reportGrammarTestError(filename, testCase, error)
        return TestFailed
      })
  }),
  concurrencyLimit
)
```

**Comment by PanAeon** [comment]
Hmm, I can't reproduce this with `scala` syntax even with thousands of tests. Nice catch anyway, I'll use `p-limit` module instead of the custom code.

**Comment by PanAeon** [comment]
ac760a4 should fix it. Please, reopen this issue if that didn't help
