### ISSUE TITLE
Allow asserting that a scope is not present

### ISSUE THREAD

**Issue by ayazhafiz** [PanAeon/vscode-tmgrammar-test#6]
It would be nice to have a way to assert that a scope is not present on some code; e.g. via a syntax like

```typescript
function main() {}
//       ^^^^       !comment
```

**Comment by PanAeon** [comment]
@ayazhafiz, if I understood this correctly, you can put `-` before scopes to mark them as unwanted, e.g:
```javascript
function main() {}
//       ^^^^       - comment
```

**Comment by ayazhafiz** [comment]
Great, thanks!
